In [2]:
import xarray as xr
import numpy as np
import pandas as pd
import veg_transition
import glob
from pathlib import Path

import utils

import matplotlib.pyplot as plt

In [3]:
# import matplotlib.pyplot as plt
# from IPython.display import set_matplotlib_formats
# %matplotlib inline
# set_matplotlib_formats('svg')

In [ ]:
paths = glob.glob("./sequences/*.csv")


years_mapping = {
    1: 2006,
    2: 2023,
    3: 2022,
    4: 2021,
    5: 2019,
}

seqs = {}
for p in paths:
    name = Path(p).stem
    seqs[name] = pd.read_csv(p, skiprows=1)

In [ ]:
# Define the source and output folder paths
source_folder = "/Users/dillonragar/data/tmp/cpra/AMP_SimulationResults/"
output_folder = "/Users/dillonragar/data/tmp/cpra/sequence-data/"

# Generate the combined sequence
utils.generate_combined_sequence(
    seqs["wet_sequence"],
    years_mapping,
    source_folder,
    output_folder,
)

In [4]:
Veg = veg_transition.VegTransition(config_file="./veg_config.yaml")
# Veg.step(pd.to_datetime("2021-10-01"))

2024-11-29 09:47:46,333 - VegTransition - INFO - [Timestep: N/A] - Logger setup complete.
2024-11-29 09:47:46,334 - VegTransition - INFO - [Timestep: N/A] - Loaded Configuration:
raster_data:
  dem_path: /Users/dillonragar/data/cpra/AMP_NGOM2_DEM_60m_Bilinear_Resample.tif
  wse_directory_path: /Users/dillonragar/data/tmp/cpra/AMP_SimulationResults
  veg_base_raster: /Users/dillonragar/data/cpra/AMP_10km_LULC_60m_Nearest_Resample/AMP_10kmBuffer_LULC_60m_Nearest_Resample.tif
  veg_keys: /Users/dillonragar/data/cpra/AMP_10km_LULC_60m_Nearest_Resample/AMP_10kmBuffer_LULC_60m_Nearest_Resample.tif.vat.dbf
  salinity_raster: null
simulation:
  start_date: '2021-10-01'
  end_date: '2023-10-01'
  wse_sequence_input: false
output:
  output_base: /Users/dillonragar/data/cpra/

2024-11-29 09:47:46,356 - VegTransition - INFO - [Timestep: N/A] - Model code version from git: 14ba8bf541c1965dd8b86795db760b4134f7c7d3
2024-11-29 09:47:46,471 - VegTransition - INFO - [Timestep: N/A] - Loaded DEM
2024-11-

In [5]:
Veg.run()

2024-11-29 09:47:48,481 - VegTransition - INFO - [Timestep: N/A] - Starting simulation at 2024-11-29 09:47:48. Period: 2021-10-01 - 2023-10-01
2024-11-29 09:47:48,484 - VegTransition - INFO - [Timestep: N/A] - Running model for: 3 timesteps
2024-11-29 09:47:48,484 - VegTransition - INFO - [Timestep: 2021-10-01] - starting timestep: 2021-10-01 00:00:00
2024-11-29 09:47:48,939 - VegTransition - INFO - [Timestep: 2021-10-01] - Replacing all NaN in WSE data with 0 (assuming full domain coverage.)
2024-11-29 09:47:48,941 - VegTransition - INFO - [Timestep: 2021-10-01] - Loaded HEC-RAS WSE Datset for year: 2021
2024-11-29 09:48:07,306 - VegTransition - INFO - [Timestep: 2021-10-01] - Creating depth
2024-11-29 09:48:07,833 - VegTransition - INFO - [Timestep: 2021-10-01] - Saved plot to /Users/dillonragar/data/cpra/VegOut_20241129_094746/20211001/figs/All_Types_Input.png
2024-11-29 09:48:07,834 - VegTransition - INFO - [Timestep: 2021-10-01] - Starting transitions with input type: Zone V
2024-

In [7]:
Veg.water_depth

<xarray.Dataset> Size: 392MB
Dimensions:      (time: 12, x: 1276, y: 3197)
Coordinates:
    band         int64 8B 1
  * time         (time) datetime64[ns] 96B 2022-10-01 2022-11-01 ... 2023-09-01
    spatial_ref  int64 8B 0
  * x            (x) float64 10kB 6.003e+05 6.003e+05 ... 6.767e+05 6.768e+05
  * y            (y) float64 26kB 3.432e+06 3.432e+06 ... 3.24e+06 3.24e+06
Data variables:
    WSE_MEAN     (time, y, x) float64 392MB nan nan nan nan ... nan nan nan nan

In [ ]:
water_depth["WSE_MEAN"][0]

<xarray.DataArray 'WSE_MEAN' (x: 2, y: 3)> Size: 48B
array([[0.5, 0. , 1. ],
       [0. , nan, 0. ]])
Coordinates:
    time     datetime64[ns] 8B 1999-10-01
  * x        (x) int64 16B 0 1
  * y        (y) int64 24B 0 1 2

In [ ]:
valid_wse = Veg.water_depth["WSE_MEAN"][0].notnull().values

array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]])

In [6]:
Veg.veg_keys

Value       Count                            Class
0       2    157630.0         Developed High Intensity
1       3    257499.0       Developed Medium Intensity
2       4   1006974.0          Developed Low Intensity
3       5   2075459.0             Developed Open Space
4       6   9301079.0                 Cultivated Crops
5       7   1877107.0                      Pasture/Hay
6       8    600845.0             Grassland/Herbaceous
7       9   3801217.0  Upland - Mixed Deciduous Forest
8      10    108834.0  Upland - Mixed Evergreen Forest
9      11    344885.0              Upland Mixed Forest
10     12    318343.0               Upland Scrub/Shrub
11     13    319771.0             Unconsolidated Shore
12     14   5463396.0                        Bare Land
13     15   3359267.0                           Zone V
14     16  13448360.0                          Zone IV
15     17  11371827.0                         Zone III
16     18  16333297.0                          Zone II
17     19   1337303.0                     Fresh Shrubs
18     20   3685024.0                      Fresh Marsh
19     21   5416210.0               Intermediate Marsh
20     22   3400033.0                   Brackish Marsh
21     23    426409.0                     Saline Marsh
22     24    403985.0           Palustrine Aquatic Bed
23     25      1983.0            Estuarine Aquatic Bed
24     26  28965065.0                       Open Water

In [5]:
Veg._load_veg_initial_raster()

2024-11-22 15:50:48,092 - VegTransition - INFO - [Timestep: N/A] - Loaded initial vegetation raster


array([[ 5.,  9.,  9., ..., nan, nan, nan],
       [ 5.,  5.,  5., ..., nan, nan, nan],
       [ 5.,  7.,  6., ..., nan, nan, nan],
       ...,
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan]], dtype=float32)