In [1]:
import xarray as xr
import numpy as np
import pandas as pd
import glob
from pathlib import Path
from datetime import datetime

import numpy as np
import xarray as xr
import pandas as pd

import utils
import veg_logic
import veg_transition
import hydro_logic

import matplotlib.pyplot as plt

In [ ]:
# test Zone V

# Create a small veg_type array with consistent dimensions
veg_type = np.array(
    [
        [15, 15, 0],  # Zone V pixels (15) and one non-Zone V (0)
        [0, 15, 15],  # Mixed pixels
    ]
)

# Create time range
time = pd.date_range("1999-03-01", "1999-09-30", freq="MS")  # 7 time steps

# Ensure wse_mean matches the spatial dimensions of veg_type
# Shape of wse_mean should be (2, 3, 7) to match (x, y, time)
wse_mean = np.array(
    [
        [  # x=0 row
            [
                0,
                0,
                0,
                0,
                0,
                0,
                0,
            ],  # y=0 column, time=7
            [0.0, 0.0, 0.5, 0.0, 0.5, 0.5, 0.5],  # y=1 column
            [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0],  # y=2 column
        ],
        [  # x=1 row
            [-0.5, -0.5, 0.5, -0.5, 0.5, 0.5, 0.5],  # y=0 column
            [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.5],  # y=1 column
            [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0],  # y=2 column
        ],
    ]
)

# Create xarray Dataset with consistent spatial dimensions
water_depth = xr.Dataset(
    {"WSE_MEAN": (["x", "y", "time"], wse_mean)},
    coords={
        "x": np.arange(veg_type.shape[0]),  # Match `veg_type` shape
        "y": np.arange(veg_type.shape[1]),  # Match `veg_type` shape
        "time": time,
    },
)
# reorder to match WSE data
water_depth = water_depth.transpose("time", "x", "y")

# Print test data to verify shapes
print("Veg Type Array (shape):", veg_type.shape)
print("Water Depth WSE_MEAN (shape):", wse_mean.shape)

# Ensure compatibility
assert veg_type.shape == wse_mean.shape[:2], "Spatial dimensions do not match!"


date = datetime(1999, 10, 1)

out = veg_logic.zone_v(
    veg_type=veg_type,
    water_depth=water_depth,
    date=date,
    timestep_output_dir="./",
)

print(veg_type)
print(out)

Veg Type Array (shape): (2, 3)
Water Depth WSE_MEAN (shape): (2, 3, 7)
[[15 15  0]
 [ 0 15 15]]
[[15. 16. nan]
 [nan 15. 15.]]


In [ ]:
# test Zone IV

# Create a small veg_type array with consistent dimensions
veg_type = np.array(
    [
        [16, 16, 0],  # Zone V pixels (15) and one non-Zone V (0)
        [0, 16, 16],  # Mixed pixels
    ]
)

# Create time range
time = pd.date_range("1999-03-01", "1999-09-30", freq="MS")  # 7 time steps

# Ensure wse_mean matches the spatial dimensions of veg_type
# Shape of wse_mean should be (2, 3, 7) to match (x, y, time)
wse_mean = np.array(
    [
        [  # y=1 row
            [-0.5, -0.5, 0.5, -0.5, 0.5, 0.5, 0.5],  # x=0 column, time=7
            [0.0, 0.0, 0.5, 0.0, 0.5, 0.5, 0.5],  # x=1 column
            [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0],  # x=2 column
        ],
        [  # y=0 row
            [-0.5, -0.5, 0.5, -0.5, 0.5, 0.5, 0.5],  # x y=0 column
            [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.5],  # x=1 column
            [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0],  # x=2 column
        ],
    ]
)

# Create xarray Dataset with consistent spatial dimensions
water_depth = xr.Dataset(
    {"WSE_MEAN": (["x", "y", "time"], wse_mean)},
    coords={
        "x": np.arange(veg_type.shape[0]),  # Match `veg_type` shape
        "y": np.arange(veg_type.shape[1]),  # Match `veg_type` shape
        "time": time,
    },
)
# reorder to match WSE data
water_depth = water_depth.transpose("time", "x", "y")

# Print test data to verify shapes
print("Veg Type Array (shape):", veg_type.shape)
print("Water Depth WSE_MEAN (shape):", wse_mean.shape)

# Ensure compatibility
assert veg_type.shape == wse_mean.shape[:2], "Spatial dimensions do not match!"


date = datetime(1999, 10, 1)

out = veg_logic.zone_iv(
    veg_type=veg_type,
    water_depth=water_depth,
    date=date,
    timestep_output_dir="./",
)

print(veg_type)
print(out)

Veg Type Array (shape): (2, 3)
Water Depth WSE_MEAN (shape): (2, 3, 7)
[[16 16  0]
 [ 0 16 16]]
[[17. 17. nan]
 [nan 15. 16.]]


In [31]:
# test Zone III

# Create a small veg_type array
veg_type = np.array(
    [
        [17, 17, 0],  # Zone V pixels (15) and one non-Zone V (0)
        [0, 17, 17],
    ]
)

# Create time range
time = pd.date_range("1999-03-01", "1999-09-30", freq="MS")  # 7 time steps

# Ensure wse_mean matches the spatial dimensions of veg_type
# Shape of wse_mean should be (2, 3, 7) to match (x, y, time)
wse_mean = np.array(
    [
        [  # y=1 row
            [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
            [0.0, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],  # top middle
            [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0],  # NaN
        ],
        [  # y=0 row
            [-0.5, -0.5, 0.5, 0.5, 0.5, 0.5, 0.5],  # NaN
            [1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],  # bottom middle
            [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0],
        ],
    ]
)

# Create xarray Dataset
water_depth = xr.Dataset(
    {"WSE_MEAN": (["x", "y", "time"], wse_mean)},
    coords={
        "x": np.arange(veg_type.shape[0]),
        "y": np.arange(veg_type.shape[1]),
        "time": time,
    },
)
# reorder to match WSE data
water_depth = water_depth.transpose("time", "x", "y")

# Print test data to verify shapes
print("Veg Type Array (shape):", veg_type.shape)
print("Water Depth WSE_MEAN (shape):", wse_mean.shape)
print()


date = datetime(1999, 10, 1)

out = veg_logic.zone_iii(
    veg_type=veg_type,
    water_depth=water_depth,
    # date=date,
    timestep_output_dir="./",
)

print(veg_type)
print(out)

Veg Type Array (shape): (2, 3)
Water Depth WSE_MEAN (shape): (2, 3, 7)

[[17 17  0]
 [ 0 17 17]]
[[17. 18. nan]
 [nan 16. 17.]]


In [ ]:
# Zone II

# logic error needs to be changed !

# Create a small veg_type array
veg_type = np.array(
    [
        [18, 18, 0],
        [0, 18, 18],
    ]
)

# Create time range
time = pd.date_range("1999-10-01", "2000-09-30", freq="MS")  # 7 time steps

# Ensure wse_mean matches the spatial dimensions of veg_type
# Shape of wse_mean should be (2, 3, 7) to match (x, y, time)
wse_mean = np.array(
    [
        [  # y=1 row
            [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
            [0.0, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],  # top middle
            [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.5, 0.5, 0.5, 0.5, 0.5],  # NaN
        ],
        [  # y=0 row
            [0.0, -0.0, 0.0, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],  # NaN
            [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],  # low mid
            [0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 1.0, 0.0, 0.0, 0.0],
        ],
    ]
)

# Create xarray Dataset
water_depth = xr.Dataset(
    {"WSE_MEAN": (["x", "y", "time"], wse_mean)},
    coords={
        "time": time,
        "x": np.arange(veg_type.shape[0]),
        "y": np.arange(veg_type.shape[1]),
    },
)
# reorder to match WSE data
water_depth = water_depth.transpose("time", "x", "y")

# Print test data to verify shapes
print("Veg Type Array (shape):", veg_type.shape)
print("Water Depth WSE_MEAN (shape):", wse_mean.shape)
print()


date = datetime(2000, 10, 1)

out = veg_logic.zone_ii(
    veg_type=veg_type,
    water_depth=water_depth,
    timestep_output_dir="./",
)

print(veg_type)
print(out)

Veg Type Array (shape): (2, 3)
Water Depth WSE_MEAN (shape): (2, 3, 12)

[[18 18  0]
 [ 0 18 18]]
[[18. 18. nan]
 [nan 17. 18.]]


In [5]:
# Fresh Shrub

# Create a small veg_type array
veg_type = np.array(
    [
        [19, 19, 0],
        [0, 19, 19],
    ]
)

# Create time range
time = pd.date_range("1999-10-01", "2000-09-30", freq="MS")  # 7 time steps

# Ensure wse_mean matches the spatial dimensions of veg_type
# Shape of wse_mean should be (2, 3, 7) to match (x, y, time)
wse_mean = np.array(
    [
        [  # y=1 row
            [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
            [0.0, 0.5, 0.5, 0.5, 0.5, 0.0, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],  # top middle
            [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.5, 0.5, 0.5, 0.5, 0.5],  # NaN
        ],
        [  # y=0 row
            [0.0, -0.0, 0.0, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],  # NaN
            [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],  # low mid
            [0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 1.0, 0.0, 0.0, 0.0],
        ],
    ]
)

# Create xarray Dataset
water_depth = xr.Dataset(
    {"WSE_MEAN": (["x", "y", "time"], wse_mean)},
    coords={
        "time": time,
        "x": np.arange(veg_type.shape[0]),
        "y": np.arange(veg_type.shape[1]),
    },
)
# reorder to match WSE data
water_depth = water_depth.transpose("time", "x", "y")

# Print test data to verify shapes
print("Veg Type Array (shape):", veg_type.shape)
print("Water Depth WSE_MEAN (shape):", wse_mean.shape)
print()


date = datetime(2000, 10, 1)

out = veg_logic.fresh_shrub(
    veg_type=veg_type,
    water_depth=water_depth,
    timestep_output_dir="./",
)

print(veg_type)
print(out)

Veg Type Array (shape): (2, 3)
Water Depth WSE_MEAN (shape): (2, 3, 12)

[[19 19  0]
 [ 0 19 19]]
[[20. 18. nan]
 [nan 19. 20.]]


In [45]:
# Fresh Marsh

# Create a small veg_type array
veg_type = np.array(
    [
        [20, 20, 20],
        [20, 20, 20],
    ]
)

salinity = np.array(
    [
        [3, 1, 1],
        [0, 1, 1],
    ]
)

# Create time range
time = pd.date_range("1999-10-01", "2000-09-30", freq="MS")  # 7 time steps

# Ensure wse_mean matches the spatial dimensions of veg_type
# Shape of wse_mean should be (2, 3, 7) to match (x, y, time)
wse_mean = np.array(
    [
        [  # y=1 row
            [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.0, 0.5, 0.5, 0.5, 0.5],
            [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],  # top middle
            [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.5, 0.5, 0.5, 0.5, 0.5],  # NaN
        ],
        [  # y=0 row
            [0.0, -0.0, 0.0, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],  # NaN
            [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],  # low mid
            [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0],  # low right
        ],
    ]
)

# Create xarray Dataset
water_depth = xr.Dataset(
    {"WSE_MEAN": (["x", "y", "time"], wse_mean)},
    coords={
        "time": time,
        "x": np.arange(veg_type.shape[0]),
        "y": np.arange(veg_type.shape[1]),
    },
)
# reorder to match WSE data
water_depth = water_depth.transpose("time", "x", "y")

# Print test data to verify shapes
print("Veg Type Array (shape):", veg_type.shape)
print("Water Depth WSE_MEAN (shape):", wse_mean.shape)
print()


date = datetime(2000, 10, 1)

out = veg_logic.fresh_marsh(
    veg_type=veg_type,
    water_depth=water_depth,
    salinity=salinity,
    timestep_output_dir="./",
)

print(veg_type)
print(out)

Veg Type Array (shape): (2, 3)
Water Depth WSE_MEAN (shape): (2, 3, 12)

[[20 20 20]
 [20 20 20]]
[[21. 26. 26.]
 [26. 19. 18.]]


In [58]:
# Intermediate Marsh

# Create a small veg_type array
veg_type = np.array(
    [
        [21, 21, 20],
        [21, 21, 21],
    ]
)

salinity = np.array(
    [
        [6, 1, 1],
        [0, 0.1, 1],
    ]
)

# Create time range
time = pd.date_range("1999-10-01", "2000-09-30", freq="MS")  # 7 time steps

# Ensure wse_mean matches the spatial dimensions of veg_type
# Shape of wse_mean should be (2, 3, 7) to match (x, y, time)
wse_mean = np.array(
    [
        [  # y=1 row
            [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.0, 0.0, 0.0, 0.0, 0.5, 0.5],
            [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.0, 0.0, 0.0, 0.5, 0.5],  # top middle
            [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.5, 0.5, 0.5, 0.5, 0.5],  # NaN
        ],
        [  # y=0 row
            [0.0, -0.0, 0.0, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],  # NaN
            [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],  # low mid
            [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0],  # low right
        ],
    ]
)

# Create xarray Dataset
water_depth = xr.Dataset(
    {"WSE_MEAN": (["x", "y", "time"], wse_mean)},
    coords={
        "time": time,
        "x": np.arange(veg_type.shape[0]),
        "y": np.arange(veg_type.shape[1]),
    },
)
# reorder to match WSE data
water_depth = water_depth.transpose("time", "x", "y")

# Print test data to verify shapes
print("Veg Type Array (shape):", veg_type.shape)
print("Water Depth WSE_MEAN (shape):", wse_mean.shape)
print()


date = datetime(2000, 10, 1)

out = veg_logic.intermediate_marsh(
    veg_type=veg_type,
    water_depth=water_depth,
    salinity=salinity,
    timestep_output_dir="./",
)

print(veg_type)
print(out)

Veg Type Array (shape): (2, 3)
Water Depth WSE_MEAN (shape): (2, 3, 12)

[[21 21 20]
 [21 21 21]]
[[22. 21. nan]
 [26. 20. 26.]]


In [8]:
# Brackish Marsh

# Create a small veg_type array
veg_type = np.array(
    [
        [22, 22, 0],
        [22, 22, 22],
    ]
)

salinity = np.array(
    [
        [13, 6, 1],
        [0, 0.1, 1],
    ]
)

# Create time range
time = pd.date_range("1999-10-01", "2000-09-30", freq="MS")  # 7 time steps

# Ensure wse_mean matches the spatial dimensions of veg_type
# Shape of wse_mean should be (2, 3, 7) to match (x, y, time)
wse_mean = np.array(
    [
        [  # y=1 row
            [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.0, 0.0, 0.0, 0.0, 0.5, 0.5],
            [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.0, 0.0, 0.0, 0.0, 0.0],  # top middle
            [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.5, 0.5, 0.5, 0.5, 0.5],  # NaN
        ],
        [  # y=0 row
            [0.0, -0.0, 0.0, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],  # NaN
            [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.0, 0.0, 0.0, 0.0, 0.0],  # low mid
            [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0],  # low right
        ],
    ]
)

# Create xarray Dataset
water_depth = xr.Dataset(
    {"WSE_MEAN": (["x", "y", "time"], wse_mean)},
    coords={
        "time": time,
        "x": np.arange(veg_type.shape[0]),
        "y": np.arange(veg_type.shape[1]),
    },
)
# reorder to match WSE data
water_depth = water_depth.transpose("time", "x", "y")

# Print test data to verify shapes
print("Veg Type Array (shape):", veg_type.shape)
print("Water Depth WSE_MEAN (shape):", wse_mean.shape)
print()


date = datetime(2000, 10, 1)

out = veg_logic.brackish_marsh(
    veg_type=veg_type,
    water_depth=water_depth,
    salinity=salinity,
    timestep_output_dir="./",
)

print(veg_type)
print(out)

Veg Type Array (shape): (2, 3)
Water Depth WSE_MEAN (shape): (2, 3, 12)

[[22 22  0]
 [22 22 22]]
[[23. 22. nan]
 [26. 21. 26.]]


In [15]:
# Saline Marsh

# Create a small veg_type array
veg_type = np.array(
    [
        [23, 23, 0],
        [23, 23, 23],
    ]
)

salinity = np.array(
    [
        [13, 6, 1],
        [0, 0.1, 1],
    ]
)

# Create time range
time = pd.date_range("1999-10-01", "2000-09-30", freq="MS")  # 7 time steps

# Ensure wse_mean matches the spatial dimensions of veg_type
# Shape of wse_mean should be (2, 3, 7) to match (x, y, time)
wse_mean = np.array(
    [
        [  # y=1 row
            [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.0, 0.0, 0.0, 0.0, 0.5, 0.5],
            [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.0, 0.0, 0.0, 0.0, 0.0],  # top middle
            [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.5, 0.5, 0.5, 0.5, 0.5],  # NaN
        ],
        [  # y=0 row
            [0.0, -0.0, 0.0, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],  # NaN
            [np.nan, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.0, 0.0, 0.0, 0.0, 0.0],  # low mid
            [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0],  # low right
        ],
    ]
)

# Create xarray Dataset
water_depth = xr.Dataset(
    {"WSE_MEAN": (["x", "y", "time"], wse_mean)},
    coords={
        "time": time,
        "x": np.arange(veg_type.shape[0]),
        "y": np.arange(veg_type.shape[1]),
    },
)
# reorder to match WSE data
water_depth = water_depth.transpose("time", "x", "y")

# Print test data to verify shapes
print("Veg Type Array (shape):", veg_type.shape)
print("Water Depth WSE_MEAN (shape):", wse_mean.shape)
print()


date = datetime(2000, 10, 1)

out = veg_logic.saline_marsh(
    veg_type=veg_type,
    water_depth=water_depth,
    salinity=salinity,
    timestep_output_dir="./",
)

print(veg_type)
print(out)

Veg Type Array (shape): (2, 3)
Water Depth WSE_MEAN (shape): (2, 3, 12)

[[23 23  0]
 [23 23 23]]
[[23. 22. nan]
 [26. nan 26.]]


In [29]:
# Water

# Create a small veg_type array
veg_type = np.array(
    [
        [26, 26, 0],
        [26, 26, 26],
    ]
)

salinity = np.array(
    [
        [1, 4, 1],
        [9, 14, 1],
    ]
)

# Create time range
time = pd.date_range("1999-10-01", "2000-09-30", freq="MS")  # 7 time steps

# Ensure wse_mean matches the spatial dimensions of veg_type
# Shape of wse_mean should be (2, 3, 7) to match (x, y, time)
wse_mean = np.array(
    [
        [  # y=1 row
            [0.01, 0.01, 0.01, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.08],
            [0.01, 0.01, 0.01, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.08],
            [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.5, 0.5, 0.5, 0.5, 0.5],  # NaN
        ],
        [  # y=0 row
            [0.01, 0.01, 0.01, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.08],
            [0.01, 0.01, 0.01, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.08],
            [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0],  # low right
        ],
    ]
)

# Create xarray Dataset
water_depth = xr.Dataset(
    {"WSE_MEAN": (["x", "y", "time"], wse_mean)},
    coords={
        "time": time,
        "x": np.arange(veg_type.shape[0]),
        "y": np.arange(veg_type.shape[1]),
    },
)
# reorder to match WSE data
water_depth = water_depth.transpose("time", "x", "y")

# Print test data to verify shapes
print("Veg Type Array (shape):", veg_type.shape)
print("Water Depth WSE_MEAN (shape):", wse_mean.shape)
print()


date = datetime(2000, 10, 1)

out = veg_logic.water(
    veg_type=veg_type,
    water_depth=water_depth,
    salinity=salinity,
    timestep_output_dir="./",
)

print(veg_type)
print(out)

Veg Type Array (shape): (2, 3)
Water Depth WSE_MEAN (shape): (2, 3, 12)

[[26 26  0]
 [26 26 26]]
[[20. 21. nan]
 [22. 23. 26.]]
