In [ ]:
import xarray as xr
import numpy as np
import pandas as pd
import glob
from pathlib import Path
from datetime import datetime

import numpy as np
import xarray as xr
import pandas as pd

import utils
import veg_logic
import veg_transition

import matplotlib.pyplot as plt

ImportError: attempted relative import with no known parent package

In [ ]:
# test Zone V

# Create a small veg_type array with consistent dimensions
veg_type = np.array(
    [
        [15, 15, 0],  # Zone V pixels (15) and one non-Zone V (0)
        [0, 15, 15],  # Mixed pixels
    ]
)

# Create time range
time = pd.date_range("1999-03-01", "1999-09-30", freq="MS")  # 7 time steps

# Ensure wse_mean matches the spatial dimensions of veg_type
# Shape of wse_mean should be (2, 3, 7) to match (x, y, time)
wse_mean = np.array(
    [
        [  # x=0 row
            [
                0,
                0,
                0,
                0,
                0,
                0,
                0,
            ],  # y=0 column, time=7
            [0.0, 0.0, 0.5, 0.0, 0.5, 0.5, 0.5],  # y=1 column
            [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0],  # y=2 column
        ],
        [  # x=1 row
            [-0.5, -0.5, 0.5, -0.5, 0.5, 0.5, 0.5],  # y=0 column
            [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.5],  # y=1 column
            [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0],  # y=2 column
        ],
    ]
)

# Create xarray Dataset with consistent spatial dimensions
water_depth = xr.Dataset(
    {"WSE_MEAN": (["x", "y", "time"], wse_mean)},
    coords={
        "x": np.arange(veg_type.shape[0]),  # Match `veg_type` shape
        "y": np.arange(veg_type.shape[1]),  # Match `veg_type` shape
        "time": time,
    },
)
# reorder to match WSE data
water_depth = water_depth.transpose("time", "x", "y")

# Print test data to verify shapes
print("Veg Type Array (shape):", veg_type.shape)
print("Water Depth WSE_MEAN (shape):", wse_mean.shape)

# Ensure compatibility
assert veg_type.shape == wse_mean.shape[:2], "Spatial dimensions do not match!"


date = datetime(1999, 10, 1)

out = veg_logic.zone_v(
    veg_type=veg_type,
    water_depth=water_depth,
    date=date,
    timestep_output_dir="./",
)

print(veg_type)
print(out)

Veg Type Array (shape): (2, 3)
Water Depth WSE_MEAN (shape): (2, 3, 7)
[[15 15  0]
 [ 0 15 15]]
[[15. 16. nan]
 [nan 15. 15.]]


In [ ]:
# test Zone IV

# Create a small veg_type array with consistent dimensions
veg_type = np.array(
    [
        [16, 16, 0],  # Zone V pixels (15) and one non-Zone V (0)
        [0, 16, 16],  # Mixed pixels
    ]
)

# Create time range
time = pd.date_range("1999-03-01", "1999-09-30", freq="MS")  # 7 time steps

# Ensure wse_mean matches the spatial dimensions of veg_type
# Shape of wse_mean should be (2, 3, 7) to match (x, y, time)
wse_mean = np.array(
    [
        [  # y=1 row
            [-0.5, -0.5, 0.5, -0.5, 0.5, 0.5, 0.5],  # x=0 column, time=7
            [0.0, 0.0, 0.5, 0.0, 0.5, 0.5, 0.5],  # x=1 column
            [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0],  # x=2 column
        ],
        [  # y=0 row
            [-0.5, -0.5, 0.5, -0.5, 0.5, 0.5, 0.5],  # x y=0 column
            [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.5],  # x=1 column
            [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0],  # x=2 column
        ],
    ]
)

# Create xarray Dataset with consistent spatial dimensions
water_depth = xr.Dataset(
    {"WSE_MEAN": (["x", "y", "time"], wse_mean)},
    coords={
        "x": np.arange(veg_type.shape[0]),  # Match `veg_type` shape
        "y": np.arange(veg_type.shape[1]),  # Match `veg_type` shape
        "time": time,
    },
)
# reorder to match WSE data
water_depth = water_depth.transpose("time", "x", "y")

# Print test data to verify shapes
print("Veg Type Array (shape):", veg_type.shape)
print("Water Depth WSE_MEAN (shape):", wse_mean.shape)

# Ensure compatibility
assert veg_type.shape == wse_mean.shape[:2], "Spatial dimensions do not match!"


date = datetime(1999, 10, 1)

out = veg_logic.zone_iv(
    veg_type=veg_type,
    water_depth=water_depth,
    date=date,
    timestep_output_dir="./",
)

print(veg_type)
print(out)

Veg Type Array (shape): (2, 3)
Water Depth WSE_MEAN (shape): (2, 3, 7)
[[16 16  0]
 [ 0 16 16]]
[[17. 17. nan]
 [nan 15. 16.]]


In [11]:
# test Zone III

# Create a small veg_type array
veg_type = np.array(
    [
        [17, 17, 0],  # Zone V pixels (15) and one non-Zone V (0)
        [0, 17, 17],
    ]
)

# Create time range
time = pd.date_range("1999-03-01", "1999-09-30", freq="MS")  # 7 time steps

# Ensure wse_mean matches the spatial dimensions of veg_type
# Shape of wse_mean should be (2, 3, 7) to match (x, y, time)
wse_mean = np.array(
    [
        [  # y=1 row
            [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
            [0.0, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],  # top middle
            [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0],  # NaN
        ],
        [  # y=0 row
            [-0.5, -0.5, 0.5, 0.5, 0.5, 0.5, 0.5],  # NaN
            [1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],  # bottom middle
            [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0],
        ],
    ]
)

# Create xarray Dataset
water_depth = xr.Dataset(
    {"WSE_MEAN": (["x", "y", "time"], wse_mean)},
    coords={
        "x": np.arange(veg_type.shape[0]),
        "y": np.arange(veg_type.shape[1]),
        "time": time,
    },
)
# reorder to match WSE data
water_depth = water_depth.transpose("time", "x", "y")

# Print test data to verify shapes
print("Veg Type Array (shape):", veg_type.shape)
print("Water Depth WSE_MEAN (shape):", wse_mean.shape)
print()


date = datetime(1999, 10, 1)

out = veg_logic.zone_iii(
    veg_type=veg_type,
    water_depth=water_depth,
    date=date,
    timestep_output_dir="./",
)

print(veg_type)
print(out)

Veg Type Array (shape): (2, 3)
Water Depth WSE_MEAN (shape): (2, 3, 7)

[[17 17  0]
 [ 0 17 17]]
[[17. 18. nan]
 [nan 16. 17.]]


In [ ]:
# Create a small veg_type array
veg_type = np.array(
    [
        [18, 18, 0],
        [0, 18, 18],
    ]
)

# Create time range
time = pd.date_range("1999-10-01", "2000-09-30", freq="MS")  # 7 time steps

# Ensure wse_mean matches the spatial dimensions of veg_type
# Shape of wse_mean should be (2, 3, 7) to match (x, y, time)
wse_mean = np.array(
    [
        [  # y=1 row
            [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
            [0.0, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],  # top middle
            [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.5, 0.5, 0.5, 0.5, 0.5],  # NaN
        ],
        [  # y=0 row
            [0.0, -0.0, 0.0, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],  # NaN
            [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],  # low mid
            [0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 1.0, 0.0, 0.0, 0.0],
        ],
    ]
)

# Create xarray Dataset
water_depth = xr.Dataset(
    {"WSE_MEAN": (["x", "y", "time"], wse_mean)},
    coords={
        "time": time,
        "x": np.arange(veg_type.shape[0]),
        "y": np.arange(veg_type.shape[1]),
    },
)
# reorder to match WSE data
water_depth = water_depth.transpose("time", "x", "y")

# Print test data to verify shapes
print("Veg Type Array (shape):", veg_type.shape)
print("Water Depth WSE_MEAN (shape):", wse_mean.shape)
print()


date = datetime(2000, 10, 1)

out = veg_logic.zone_ii(
    veg_type=veg_type,
    water_depth=water_depth,
    date=date,
    timestep_output_dir="./",
)

print(veg_type)
print(out)

Veg Type Array (shape): (2, 3)
Water Depth WSE_MEAN (shape): (2, 3, 12)

[[18 18  0]
 [ 0 18 18]]
[[18. 18. nan]
 [nan nan 18.]]
